import os
from dotenv import load_dotenv

load_dotenv()

MONDAY_TOKEN = os.getenv("MONDAY_TOKEN")
MONDAY_BOARD_ID_PERS = os.getenv("MONDAY_BOARD_ID_PERS")
MONDAY_BOARD_ID_INDICADOR = os.getenv("MONDAY_BOARD_ID_INDICADOR")
MONDAY_BOARD_ID_DEV = os.getenv("MONDAY_BOARD_ID_DEV")

HUBSPOT_TOKEN = os.getenv("HUBSPOT_TOKEN")
HUBSPOT_PIPELINE_ID_NII = os.getenv("HUBSPOT_PIPELINE_ID_NII")

HUBSPOT_STAGE_ID_NOVO = os.getenv("HUBSPOT_STAGE_ID_NOVO")
HUBSPOT_STAGE_ID_ANALISE = os.getenv("HUBSPOT_STAGE_ID_ANALISE")
HUBSPOT_STAGE_ID_EXECUCAO = os.getenv("HUBSPOT_STAGE_ID_EXECUCAO")
HUBSPOT_STAGE_ID_VALID_INTERNA = os.getenv("HUBSPOT_STAGE_ID_VALID_INTERNA")
HUBSPOT_STAGE_ID_HOMOLOGACAO = os.getenv("HUBSPOT_STAGE_ID_HOMOLOGACAO")
HUBSPOT_STAGE_ID_PUBLICACAO = os.getenv("HUBSPOT_STAGE_ID_PUBLICACAO")
HUBSPOT_STAGE_ID_AGUARD_INFRA = os.getenv("HUBSPOT_STAGE_ID_AGUARD_INFRA")
HUBSPOT_STAGE_ID_AGUARD_CLIENTE = os.getenv("HUBSPOT_STAGE_ID_AGUARD_CLIENTE")
HUBSPOT_STAGE_ID_AGUARD_DEV = os.getenv("HUBSPOT_STAGE_ID_AGUARD_DEV")
HUBSPOT_STAGE_ID_FINALIZADO = os.getenv("HUBSPOT_STAGE_ID_FINALIZADO")

MONDAY_BOARD_ID_PERSONALIZACAO = os.getenv("MONDAY_BOARD_ID_PERS", "8519439821")
MONDAY_ACCOUNT_SLUG = os.getenv("MONDAY_ACCOUNT_SLUG", "globalthings")

MONDAY_STATUS_HORAS_RECEBIDAS = os.getenv("MONDAY_STATUS_HORAS_RECEBIDAS", "Horas Recebidas")
MONDAY_STATUS_EM_LEVANTAMENTO = os.getenv("MONDAY_STATUS_EM_LEVANTAMENTO", "Em levatamento de Horas")
MONDAY_STATUS_AGUARDANDO_APROVACAO = os.getenv(
    "MONDAY_STATUS_AGUARDANDO_APROVACAO",
    "Aguardando Aprovação",
)

HUBSPOT_TIPO_TICKET_PERSONALIZACAO = os.getenv(
    "HUBSPOT_TIPO_TICKET_PERSONALIZACAO",
    "Melhoria/Personalização",
)
HUBSPOT_TIPO_SOLICITACAO_PERSONALIZACAO = os.getenv(
    "HUBSPOT_TIPO_SOLICITACAO_PERSONALIZACAO",
    "Melhoria/Personalização",
)
